
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpryayfndzfeyfrnsesr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwcnlheWZuZHpmZXlmcm5zZXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDMzODIsImV4cCI6MjA1ODkxOTM4Mn0.1lZRuvM31rRUqWf-ivBGt4_5q0OwjjWaYVKq3fRAlOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
